apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cd-pipeline
spec:
  params:
    - name: repo-url
    - name: branch
      default: "master"
  tasks:
    - name: clone
      taskRef:
        name: checkout
      params:
        - name: repo-url
          value: "$(params.repo-url)"
        - name: branch
          value: "$(params.branch)"

    - name: lint
      taskRef:
        name: echo
      params:
        - name: message
          value: "Linting the code..."
      runAfter:
        - clone
    - name: tests
      taskRef:
        name: echo
      params:
        - name: message
          value: "Running tests..."
      runAfter:
        - lint
    - name: setup-maven
      taskRef:
        name: echo
      params:
        - name: message
          value: "Setting up Maven..."
      runAfter:
        - tests
    - name: build
      taskRef:
        name: echo
      params:
        - name: message
          value: "Building image for $(params.repo-url)..."
      runAfter:
        - setup-maven

    - name: deploy
      taskRef:
        name: echo
      params:
        - name: message 
          value: "Deploying $(params.branch) branch of $(params.repo-url)..."
      runAfter:
        - build
      